apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.app.securityContext.runAsNonRoot }}
        fsGroup: {{ .Values.app.securityContext.fsGroup }}
      containers:
        - name: {{ .Values.app.name }}-container
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.service.targetPort }}

          # ---- DB configuration from Kubernetes Secret ----
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}

          securityContext:
            runAsUser: {{ .Values.app.securityContext.runAsUser }}
            allowPrivilegeEscalation: {{ .Values.app.securityContext.allowPrivilegeEscalation }}

          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.service.targetPort }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.app.probes.readiness.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.service.targetPort }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.app.probes.liveness.failureThreshold }}
