{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: {{ .Values.mysql.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.secrets.database }}
  MYSQL_USER: {{ .Values.mysql.secrets.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.password }}
  DB_HOST: {{ .Values.mysql.secrets.dbHost }}
{{- end }}
