# Application Configuration
app:
  name: webapp
  replicaCount: 1
  
  image:
    repository: thumunavyasri/fastapi-docker-app
    tag: latest
    pullPolicy: Always
  
  service:
    type: NodePort
    port: 8000
    targetPort: 8000
    nodePort: 30007
  
  resources:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 400Mi
  
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 2000
    allowPrivilegeEscalation: false
  
  probes:
    readiness:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      path: /
      initialDelaySeconds: 15
      periodSeconds: 20
      failureThreshold: 3

# HPA Configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 95
  targetMemoryUtilizationPercentage: 95

# MySQL Configuration
mysql:
  enabled: true
  name: mysql
  
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  service:
    port: 3306
  
  persistence:
    enabled: true
    size: 128Mi
    accessMode: ReadWriteOnce
  
  # MySQL credentials (base64 encoded)
  secrets:
    rootPassword: c3VwZXJzZWNyZXQ=      # supersecret
    database: YXBwX2Ri                  # app_db
    user: YXBwX3VzZXI=                  # app_user
    password: YXBwX3Bhc3M=              # app_pass
